// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmiztetkptobnisfxplw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtaXp0ZXRrcHRvYm5pc2Z4cGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDI5MTksImV4cCI6MjA3MDc3ODkxOX0.on7tpOreVl6F7iQYibo63GzjPrgDAzWBGTap4d4oNIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});